import express from "express";
import multer from "multer";
import processTXT from "./processTxt";
import processPDF from "./processPdfWithOCR/index";
import addEntryForLeg from "./addEntryForLeg";
import addOperator from "./addOperator";
import confirmMissions from "./confirmMissions";
import deleteOperator from "./deleteOperator";
import deleteEntry from "./deleteEntry";
import getAirport from "./getAirport";
import getActualMissions from "./getActualMissions";
import getConfig from "./getConfig";
import getEntriesForLeg from "./getEntriesForLeg";
import getMOTD from "./getMOTD";
import getMissions from "./getMissions";
import getMissionsOnDate from "./getMissionsOnDate";
import getMissionsUpcoming from "./getMissionsUpcoming";
import getMissionsFromDate from "./getMissionsFromDate";
import getMissionsFromDateForOperator from "./getMissionsFromDateForOperator";
import getMostRecentMission from "./getMostRecentMission";
import getLeg from "./getLeg";
import getLegs from "./getLegs";
import getCountryCodes from "./getCountryCodes";
import getOperators from "./getOperators";
import getLegsByMission from "./getLegsByMission";
import deleteMission from "./deleteMission";
import saveLegRoute from "./saveLeg";
import saveConfig from "./saveConfig";
import updateMission from "./updateMission";
import updateOperator from "./updateOperator";
import updateMOTD from "./updateMOTD";

const upload = multer({ dest: "./processPdfWithOCR/pdfs/" }); // dest: "uploads/" for pdfs {deprecated}
const routes = express.Router();

routes.post("/getAirport", getAirport);
// routes.post("/processTXT", upload.single("file"), processTXT);
routes.post("/processPDF", upload.single("file"), processPDF);
routes.post("/confirmMissions", confirmMissions);
routes.post("/updateMission", updateMission);
routes.post("/deleteMission", deleteMission);
routes.post("/deleteOperator", deleteOperator);
routes.post("/addEntryForLeg", addEntryForLeg);
routes.post("/addOperator", addOperator);
routes.post("/saveLeg", saveLegRoute);
routes.post("/saveConfig", saveConfig);
routes.post("/deleteEntry", deleteEntry);
routes.post("/updateOperator", updateOperator);
routes.post("/updateMOTD", updateMOTD);
routes.get("/getActualMissions", getActualMissions);
routes.get("/getLegsByMission", getLegsByMission);
routes.get("/getConfig", getConfig);
routes.get("/getMissions", getMissions);
routes.get("/getMissionsOnDate", getMissionsOnDate);
routes.get("/getMissionsUpcoming", getMissionsUpcoming);
routes.get("/getMostRecentMission", getMostRecentMission);
routes.get("/getMissionsFromDate", getMissionsFromDate);
routes.get("/getMissionsFromDateForOperator", getMissionsFromDateForOperator);
routes.get("/getOperators", getOperators);
routes.get("/getCountryCodes", getCountryCodes);
routes.get("/getLegs", getLegs);
routes.get("/getLeg", getLeg);
routes.get("/getEntriesForLeg", getEntriesForLeg);
routes.get("/getMOTD", getMOTD);

export default routes;
